version: 2
jobs:
  foo:
    docker:
      - image: circleci/clojure:lein-2.9.0
    steps:
      - checkout
      - run: sleep 30
  bar:
    docker:
      - image: circleci/clojure:lein-2.9.0
    steps:
      - checkout
      - run: sleep 60
  bar1:
    docker:
      - image: circleci/clojure:lein-2.9.0
    steps:
      - checkout
      - run: "true"
workflows:
  version: 2
  build_and_test:
    jobs:
      - foo
      - bar
          requires:
            - bar1
