version: 2
jobs:
  create:
    docker:
      - image: circleci/clojure:lein-2.9.0
    steps:
      - checkout
      - run: echo hello > /tmp/test
      - persist_to_workspace:
         root: /tmp
         paths:
           - test
  read:
    docker:
      - image: circleci/clojure:lein-2.9.0
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - run: cat /tmp/test
  tag-only:
    docker:
      - image: circleci/clojure:lein-2.9.0
    steps:
      - checkout
      - run: "true"
workflows:
  version: 2
  build_and_test:
    jobs:
      - create:
          filters:
            tags:
              only: /.*/
      - read:
          filters:
            tags:
              only: /.*/
          requires:
            - create
      - tag-only:
          requires:
            - read
          filters:
            tags:
              only: /v.+/
