this should be invalid
version: 2.1
jobs:
  create:
    docker:
      - image: circleci/clojure:lein-2.9.0
    steps:
      - checkout
      - run: echo hello > /tmp/test
      - persist_to_workspace:
         root: /tmp
         paths:
           - test
  read:
    docker:
      - image: circleci/clojure:lein-2.9.0
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - run: cat /tmp/test
workflows:
  version: 2
  build_and_test:
    jobs:
      - create
      - read:
          requires:
            - create
