version: 2.1
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.9.0
    steps:
      - checkout
      - run: echo hello
  test:
    docker:
      - image: circleci/clojure:lein-2.9.0
    steps:
      - checkout
      - run: "false"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
      - hold:
          type: approval
          requires:
            - build