version: 2
jobs:
  read:
    docker:
      - image: circleci/clojure:lein-2.9.0
    steps:
      - checkout
      - run: echo $SECRET
workflows:
  version: 2
  build_and_test:
    jobs:
      - read:
          context: bar

