version: 2
jobs:
  create:
    docker:
      - image: circleci/clojure:lein-2.9.0
    steps:
      - checkout
      - run: echo hello > /tmp/test
      - persist_to_workspace:
         root: /tmp
         paths:
           - test
  read:
    docker:
      - image: circleci/clojure:lein-2.9.0
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - run: sleep 120
  scheduled:
    docker:
      - image: circleci/clojure:lein-2.9.0
    steps:
      - checkout
      - run: true
workflows:
  version: 2
  build_and_test:
    jobs:
      - create
      - read:
          requires:
            - create
  nightly:
    jobs:
      - scheduled
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - org
